CREATE TABLE orders
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    status     INTEGER   NOT NULL CHECK (status >= 0),
    CONSTRAINT status_valid CHECK (status <= 3)
);

INSERT INTO orders (created_at, status)
VALUES (CURRENT_TIMESTAMP - INTERVAL '30 minutes', 2); -- COMPLETED

INSERT INTO orders (created_at, status)
VALUES (CURRENT_TIMESTAMP - INTERVAL '5 minutes', 1); -- IN_PROGRESS

INSERT INTO orders (created_at, status)
VALUES (CURRENT_TIMESTAMP, 0); -- NEW
